apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db/deployment.yml
  - db/service.yml
  - db/pvc.yml
  - nextcloud/pvc.yml
  - nextcloud/deployment.yml
  - nextcloud/service.yml
  - nextcloud/ingress.yml

secretGenerator:
  - name: mysql-credentials
    literals:
    - rootPassword=xxxxxxxx
    - mysqlUsername=nextcloud
    - mysqlPassword=nextcloudsupersecure!!
    - databaseName=nextcloud